/*******************************************************************************************************************************
 * @file   foc_field_weakening.c
 *
 * @brief  Source file for FOC field weakening library
 *
 * @date   2025-06-21
 * @author Aryan Kashem
 *******************************************************************************************************************************/

/* Standard library Headers */
#include <stddef.h>

/* Inter-component Headers */
#include "math_utils.h"

/* Intra-component Headers */
#include "foc_field_weakening.h"

MotorError_t field_weakening_init(struct FieldWeakeningState_t *state, const struct FieldWeakeningConfig_t *config) {
  if (state == NULL || config == NULL) {
    return MOTOR_INVALID_ARGS;
  }

  state->id_ref = 0.0f;
  state->config = config;

  return MOTOR_OK;
}

MotorError_t field_weakening_update(struct FieldWeakeningState_t *state, float vd, float vq, float vbus) {
  if (state == NULL) {
        return MOTOR_INVALID_ARGS;
    }

    /*
     * Calculate the magnitude of the motor's voltage vector
     */
    float v_mag_sq = (vd * vd) + (vq * vq);
    float v_mag = sqrtf(v_mag_sq);

    /*
     * Determine maximum voltage magnitude based on DC bus voltage and margin
     */
    float v_max_allowed = state->config->voltage_margin * vbus;

    /*
     * Determine the voltage error
     * Positive error means we are demanding too much voltage
     */
    float voltage_error = v_mag - v_max_allowed;

    /*
     * If the voltage error is positive (We are demanding too much), make Id_ref more negative
     * This reduces the flux generated by the motor, effectively reducing the maximum BEMF
     * As a result we can achieve more speed, while reducing the torque output
     */
    state->id_ref -= state->config->k_fw * voltage_error;

    /*
     * Clamp Id_ref to the configured limits where Id_min is negative, and Id_max is typically 0
     */
    state->id_ref = clamp(state->id_ref, state->config->id_min, state->config->id_max);

    return MOTOR_OK;
}
